services:
  bot:
    build: .
    container_name: bolao-bot
    restart: unless-stopped
    
    env_file:
      - ./.env
      
    volumes:
      # Persiste os dados de autenticação do WhatsApp para não precisar escanear o QR code toda vez
      - bot-session-data:/app/baileys_auth_info
      # Persiste os logs do bot (opcional, mas bom para depuração)
      - bot-logs:/app/logs
      # Persiste os dados do banco de dados de usuários que não devem ser marcados
      - bot-database:/app/dist/database
      
    networks:
      - bot-network

volumes:
  bot-session-data:
    driver: local
  bot-logs:
    driver: local
  bot-database:
    driver: local

networks:
  bot-network:
    driver: bridge