export const emojisTimes = {
  Palmeiras: '🐷',
  Flamengo: '🐦‍⬛',
  Corinthians: '🦅',
  'São Paulo': '👼',
  Santos: '🐳',
  'Vasco da Gama': '⛵',
  Fluminense: '🇭🇺',
  Botafogo: '⭐',
  Cruzeiro: '🦊',
  'Atlético-MG': '🐔',
  Grêmio: '⚔️',
  Internacional: '🔴',
  Bahia: '🦸',
  Ceará: '👴',
  Fortaleza: '🦁',
  Bragantino: '🐂',
  Juventude: '🇳🇬',
  Vitória: '🦁',
  Sport: '🦁',
  Mirassol: '🌞',
};
